#Project Euler Question 2

#Each new term in the Fibonacci sequence is generated by adding the previous 
#two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed 
#four million, find the sum of the even-valued terms.

#Initialise these values as the first and second even fibonacci numbers
older_even_term = 2
recent_even_term = 8

limit = 4000000 
answer = older_even_term + recent_even_term
next_even_term = 4*recent_even_term + older_even_term

while next_even_term <= limit:
    answer += next_even_term
    older_even_term = recent_even_term
    recent_even_term = next_even_term
    next_even_term = 4*recent_even_term + older_even_term
    
print(answer)