#Project Euler Question 2

#Each new term in the Fibonacci sequence is generated by adding the previous 
#two terms. 
#By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed 
#four million, find the sum of the even-valued terms.

#Initialise these values as the first and second even fibonacci numbers
older_fib_term = 1
recent_fib_term = 2

limit = 4000000 
answer = 2 #First even fibonacci
next_fib_term = older_fib_term + recent_fib_term

while next_fib_term <= limit:
    if next_fib_term % 2 == 0:
        answer += next_fib_term    
    
    older_fib_term = recent_fib_term
    recent_fib_term = next_fib_term
    next_fib_term = older_fib_term + recent_fib_term
    
print(answer)